// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "sa-east-1",
    "aws_content_delivery_bucket": "concil-api",
    "aws_content_delivery_bucket_region": "sa-east-1",
    "aws_content_delivery_url": "https://d1uygdns0emm5c.cloudfront.net"
};


export default awsmobile;
